/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'country' : string,
  'city' : string,
  'name' : string,
  'email' : [] | [string],
  'address' : string,
  'phone' : string,
}
export interface ServiceRequest {
  'id' : string,
  'serviceType' : string,
  'data' : string,
  'submittedAt' : string,
  'submittedBy' : Principal,
}
export interface ShipmentDetails {
  'weight' : number,
  'description' : string,
  'deliveryType' : { 'express' : null } |
    { 'priority' : null } |
    { 'standard' : null },
  'quantity' : bigint,
  'category' : { 'cargo' : null } |
    { 'freight' : null } |
    { 'document' : null } |
    { 'parcel' : null },
}
export interface ShippingOrder {
  'id' : string,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'out_for_delivery' : null } |
    { 'in_transit' : null } |
    { 'delivered' : null } |
    { 'processing' : null },
  'owner' : Principal,
  'shipment' : ShipmentDetails,
  'sender' : Address,
  'receiver' : Address,
}
export interface UserProfile {
  'country' : string,
  'name' : string,
  'email' : string,
  'passwordHash' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createShippingOrder' : ActorMethod<[ShippingOrder], undefined>,
  'getAllServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getAllShippingOrders' : ActorMethod<[], Array<ShippingOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getMyShippingOrders' : ActorMethod<[], Array<ShippingOrder>>,
  'getShippingOrder' : ActorMethod<[string], ShippingOrder>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitServiceRequest' : ActorMethod<[ServiceRequest], undefined>,
  'updateOrderStatus' : ActorMethod<
    [
      string,
      { 'cancelled' : null } |
        { 'pending' : null } |
        { 'out_for_delivery' : null } |
        { 'in_transit' : null } |
        { 'delivered' : null } |
        { 'processing' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];